### ISSUE TITLE
Add CSS Styles for index page

### ISSUE THREAD

**Issue by ruf-io** [do-community/developer-glossary#1]
Right now the index page is just HTML
![image](https://user-images.githubusercontent.com/11527560/94982964-da96e280-050c-11eb-9a1c-b1ace6761b54.png)

We can make it prettier!

Add styles in /static/css/main.css

Let's keep it accessible, and working well on mobile.

**Comment by naomi-lgbt** [comment]
👋🏻 
Mind if I give this a shot?

**Comment by ruf-io** [comment]
@nhcarrigan go for it! Someone already added bootstrap but I think it could be much improved.

**Comment by naomi-lgbt** [comment]
Nice! 😁 Haven't used Bootstrap in a while - good excuse to dust off those skills.
