### ISSUE TITLE
Come up with a way to display "Abbreviation" frontmatter when it is defined for a term

### ISSUE THREAD

**Issue by ruf-io** [do-community/developer-glossary#10]
We have an optional [hugo front matter](https://gohugo.io/content-management/front-matter/) variable of `abbreviation` available. When a term has an abbreviation the author can write it in as a string, see [Command-Line Interface](https://github.com/do-community/developer-glossary/blob/main/content/terms/command-line-interface.md) example:

![image](https://user-images.githubusercontent.com/11527560/94995233-fcbf4d80-056a-11eb-86ed-27c6f78eea46.png)

Update the [`single.html`](https://github.com/do-community/developer-glossary/blob/main/layouts/terms/single.html) template to render this out somewhere on the page.

**Comment by InfiniteAnts** [comment]
I can handle this now that I have done synonyms. Can I be assigned to this if the synonyms PR gets approved?
