### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by ruf-io** [do-community/developer-glossary#11]
We need a code of conduct!

Look around for a good Code of Conduct and add it following GitHub best practices.

Once the PR is open we can talk through whether it's a good fit.

**Comment by hot9cups** [comment]
I'd like to work on this

**Comment by timmybytes** [comment]
Hey there! I love the idea of a developer glossary, and I'd like to help out by finding an appropriate Code of Conduct for the project. I've already found a few examples I think would work well after being consolidated, but I wondered if there were any preferences you have for listing particular response team member(s)?
