### ISSUE TITLE
Add all the wonderful meta tags to make glossary.dev look pretty when you post it to fb/twitter/etc..

### ISSUE THREAD

**Issue by ruf-io** [do-community/developer-glossary#13]
Here's what https://www.glossary.dev looks like when you preview it in the twitter link validator:

https://cards-dev.twitter.com/validator

![image](https://user-images.githubusercontent.com/11527560/94995575-401abb80-056d-11eb-90d3-c4c6646bf0c5.png)

That could be better!

Use a tool like https://metatags.io/ to generate some useful meta tags to add to glossary.dev - I think we'd want to include them in the https://github.com/do-community/developer-glossary/blob/main/layouts/index.html file to start, and we can break it out into it's own partial later.

**Comment by JordanaHarrison** [comment]
I'm interested in this, can you assign to me? Also these tags usually include an image to represent the site/page. Is there an image or a logo I could use?

**Comment by dr5hn** [comment]
@JordanaHarrison I already started working on it. Can you please try another one ?

**Comment by ruf-io** [comment]
@JordanaHarrison why don't you take the meta tags for index page. @dr5hn create meta tags for the `single.html` template that represents each individual term.

For images, go wild, make something up and we can always improve it later.

**Comment by ruf-io** [comment]
@dr5hn comment in this issue and I'll assign it to you https://github.com/do-community/developer-glossary/issues/20

**Comment by dr5hn** [comment]
@ruf-io Anyone is fine for me. 😁

**Comment by ruf-io** [comment]
@dr5hn comment into that thread https://github.com/do-community/developer-glossary/issues/20 so I can assign you to it :)

**Comment by JordanaHarrison** [comment]
Great, I'll do the index then 👍
