### ISSUE TITLE
Dates in the future are preventing some terms from rendering

### ISSUE THREAD

**Issue by ruf-io** [do-community/developer-glossary#14]
I think the `date` frontmatter is useful to tell us when the term was first added, but I noticed with @hot9cups contribution, they are in a timezone ahead of me so when I built the site, hugo decided not to render the new terms because the publish date was "in the future"

This will fix itself in a few hours, but in the meantime maybe we should come up with a fix that makes adding dates more intuitive.

I think we need to either update hugo config and logic to render everything, independent of date. OR we need to just change date to something much simpler. Like maybe change it from a timestamp to a date only.

**Comment by RascalTwo** [comment]
Hey, I can do this, found the [buildFuture](https://gohugo.io/getting-started/configuration/) config option - tested it out and simply setting this to `true` fixes this issue.

***

While moving to date-only would likely reduce the number of such missed builds, it won't prevent them all.

For example - someone adds content with a date of `2020-10-04` when it's 1 AM for them, all the timezones in which it's still `2020-10-03` will not build the new content.

***

I'm not familiar enough with Hugo to offer any other solutions besides the `buildFuture` one.

**Comment by ruf-io** [comment]
@RascalTwo good find - the `buildFuture` option is specified in the config or in the build command? If it's config, feel free to submit a PR!

**Comment by RascalTwo** [comment]
Thanks, and it's actually available as both a [command flag (`-F`/`--buildFuture`)](https://gohugo.io/commands/hugo/#options) and a [config option](https://gohugo.io/getting-started/configuration/).

> No direct anchor links exist for either so you'll have to search the pages for `buildFuture` to jump to them.
