### ISSUE TITLE
Style the Term page

### ISSUE THREAD

**Issue by ruf-io** [do-community/developer-glossary#2]
Right now a term page is just HTML
![image](https://user-images.githubusercontent.com/11527560/94983082-87715f80-050d-11eb-9981-d32aded916f1.png)

We can make it prettier!

Style it following the lead set in the [index styles](https://github.com/do-community/developer-glossary/issues/1) PR, and make it accessible and responsive!

**Comment by ruf-io** [comment]
This shouldn't start til the index styles are set (this issue https://github.com/do-community/developer-glossary/issues/1)

**Comment by dr5hn** [comment]
@ruf-io Fixed in #33
