### ISSUE TITLE
Write a "language use guidelines" section in readme

### ISSUE THREAD

**Issue by ruf-io** [do-community/developer-glossary#22]
Something that gives guidance on language use in definitions and examples.

I think we should strive for:
- follow code of conduct
- simple language
- avoid idioms or country-specific language

Add this as a section the readme.

**Comment by ShreyaPrabhu** [comment]
@ruf-io Can you assign this to me? I would like to contribute.

**Comment by ruf-io** [comment]
@ShreyaPrabhu all you!
