### ISSUE TITLE
BUG: Letter of alphabet shows up before each consecutive term with the same first letter

### ISSUE THREAD

**Issue by ruf-io** [do-community/developer-glossary#36]
We've finally added more than one term starting with the same letter and it exposed a bug:

![image](https://user-images.githubusercontent.com/11527560/95095283-dc24fe00-06f8-11eb-84ef-e9fc6d161502.png)

The letter `C` is only meant to show up before the FIRST term beginning with C

This code is not doing what it is intended to:

https://github.com/do-community/developer-glossary/blob/ab3220651d61a43b9d7084d6813fd45c7cc2a72e/layouts/index.html#L44-L48

Update the logic to correct, BTW here is a useful discussion of a similar problem: https://discourse.gohugo.io/t/lists-of-content-divided-by-posts-first-letter/8534

**Comment by paulmhan** [comment]
I can take a look at this for you, can you assign me?

**Comment by ruf-io** [comment]
@paulmhan done

**Comment by paulmhan** [comment]
Sorry for the delay, working on it now.
