### ISSUE TITLE
Come up with a way to display "Synonyms" frontmatter when it is defined for a term

### ISSUE THREAD

**Issue by ruf-io** [do-community/developer-glossary#8]
We have an optitional [hugo front matter](https://gohugo.io/content-management/front-matter/) variable of `synonyms` available. When a term has synonyms the author can write them in to this as an array, see [Command-Line Interface](https://github.com/do-community/developer-glossary/blob/main/content/terms/command-line-interface.md) example:

![image](https://user-images.githubusercontent.com/11527560/94995233-fcbf4d80-056a-11eb-86ed-27c6f78eea46.png)

Update the [`single.html`](https://github.com/do-community/developer-glossary/blob/main/layouts/terms/single.html) template to render this out somewhere on the page.

**Comment by InfiniteAnts** [comment]
Can I be assigned to this?
